services :
  installer :
    container_name: azuracast_installer
    image: 'ghcr.io/azuracast/azuracast:${AZURACAST_VERSION:-latest}'
    volumes:
      - './:/installer'
    restart: 'no'
    entrypoint: ''
    command: docker_installer
